version: '3'
services:
  postgres:
    container_name: postgres_chat
    image: postgres:16-alpine3.18
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=chat_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root2022
    volumes:
      - chat_management:/var/lib/postgresql/data
  app:
    container_name: chat_management
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_chat:5432/chat_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root2022
    links:
      - postgres
volumes:
  chat_management: