version: '3'
services:
  postgres:
    container_name: postgres_monitoring
    image: postgres:16-alpine3.18
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=monitoring_management
      - POSTGRES_USER=****
      - POSTGRES_PASSWORD=****
    volumes:
      - monitoring_management:/var/lib/postgresql/data
  app:
    container_name: monitoring_management
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_monitoring:5432/monitoring_management
      - SPRING_DATASOURCE_USERNAME=****
      - SPRING_DATASOURCE_PASSWORD=****
    links:
      - postgres
volumes:
  monitoring_management: